# Generated by Django 4.2.28 on 2026-05-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مردانه'), ('female', 'زنانه')], max_length=10, null=True),
        ),
    ]
