# Generated by Django 4.2.30 on 2026-06-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_gender_alter_user_phone_number'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE accounts_user SET phone_number = '' WHERE phone_number IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
