# Generated by Django 4.2.30 on 2026-06-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_fix_phone_number_nulls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('tehran', 'تهران'), ('mashhad', 'مشهد'), ('isfahan', 'اصفهان'), ('shiraz', 'شیراز'), ('tabriz', 'تبریز'), ('qom', 'قم'), ('kashan', 'کاشان'), ('kermanshah', 'کرمانشاه'), ('bandar_abbas', 'بندرعباس'), ('ahvaz', 'اهواز'), ('yazd', 'یزد'), ('karaj', 'کرج'), ('arak', 'اراک'), ('hamedan', 'همدان'), ('khorramabad', 'خرم آباد'), ('sanandaj', 'سنندج'), ('bojnord', 'بجنورد'), ('sabzevar', 'سبزوار'), ('rasht', 'رشت'), ('babol', 'بابل'), ('gorgan', 'گرگان'), ('ramsar', 'رامسر'), ('sari', 'ساری'), ('ardabil', 'اردبیل'), ('zanjan', 'زنجان'), ('ardestan', 'اردستان'), ('bushehr', 'بوشهر'), ('khoy', 'خوی'), ('mahabad', 'مهاباد'), ('marivan', 'مریوان'), ('qaimshahr', 'قائم\u200cشهر'), ('lahijan', 'لاهیجان'), ('aliabad', 'علی\u200cآباد'), ('anzali', 'انزلی'), ('chalus', 'چالوس'), ('nowshahr', 'نوشهر'), ('neyshabur', 'نیشابور')], default='', max_length=50),
        ),
    ]
