# Generated by Django 4.2.28 on 2026-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(default='', help_text='ایمیل مشتری برای ارسال تایید', max_length=254),
        ),
    ]
