import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);
const STORAGE_KEY = 'salonify_language';

const translations = {
  fa: {
    header: {
      home: 'صفحه اصلی',
      myBookings: 'نوبت‌های من',
      ownerBookings: 'رزروهای سالن',
      admin: 'پنل مدیریت',
      support: 'پشتیبانی',
      login: 'ورود',
      signup: 'ثبت‌نام',
      logout: 'خروج از حساب',
      userAs: 'وارد شده به عنوان',
      toggle: 'English',
      theme: 'تغییر حالت تم',
      themeDark: 'تاریک',
      themeLight: 'روشن',
      supportTelegram: 'پشتیبانی تلگرام',
      mobileMenu: 'منوی موبایل',
      brandTitle: 'سالنیفای',
      brandSubtitle: 'نوبت‌دهی آنلاین',
      switchToPersian: 'تغییر به فارسی',
      switchToEnglish: 'Switch to English',
    },
    auth: {
      loginTitle: 'ورود به حساب',
      loginSubtitle: 'به نوبت‌دهی آنلاین آرایشگاه خوش آمدید',
      username: 'نام کاربری',
      email: 'ایمیل',
      password: 'رمز عبور',
      forgotPassword: 'فراموشی رمز عبور',
      submit: 'ورود به حساب',
      loading: 'در حال ورود...',
      noAccount: 'حساب کاربری ندارید؟',
      createAccount: 'یک حساب بسازید',
      quickLogin: 'ورود سریع و امن به حساب کاربری',
      resetSent: 'لینک بازیابی ارسال شد',
      resetInfo: 'اگر این حساب وجود داشته باشد، لینک بازیابی به ایمیل ثبت‌شده ارسال می‌شود.',
      resetError: 'برای ارسال لینک بازیابی، ابتدا نام کاربری را وارد کنید.',
      invalidLink: 'لینک بازیابی نامعتبر است.',
      showPassword: 'نمایش رمز عبور',
      hidePassword: 'مخفی کردن رمز عبور',
      loginSuccess: 'ورود موفقیت‌آمیز بود',
      loginFailed: 'ورود ناموفق بود. لطفاً دوباره تلاش کنید.',
      usernameMissing: 'لطفاً نام کاربری را وارد کنید',
      passwordMissing: 'لطفاً رمز عبور را وارد کنید',
      usernameInvalid: 'نام کاربری وجود ندارد یا اشتباه است',
      passwordInvalid: 'رمز عبور نادرست است',
      accountDisabled: 'این حساب کاربری غیرفعال شده است',
      networkError: 'خطای شبکه. لطفاً دوباره تلاش کنید',
      resetFailed: 'ارسال لینک بازیابی ناموفق بود. دوباره تلاش کنید.',
      resetSuccess: 'رمز عبور با موفقیت تغییر کرد.'
    },
    signup: {
      title: 'ایجاد حساب',
      subtitle: 'ثبت‌نام برای رزرو و مدیریت نوبت',
      submit: 'ثبت‌نام',
      loading: 'در حال ثبت‌نام...',
      alreadyHaveAccount: 'از قبل حساب دارید؟',
      loginLink: 'وارد شوید',
      roleCustomer: 'مشتری',
      roleOwner: 'مالک سالن',
      roleStaff: 'کارمند',
      accountType: 'نوع حساب',
      personalInfo: 'اطلاعات شخصی',
      salonInfo: 'اطلاعات سالن',
      passwordSection: 'رمز عبور',
      createAccountButton: 'ساخت حساب کاربری',
      createAccountLoading: 'در حال ساخت حساب...',
      haveAccountPrompt: 'حساب کاربری دارید؟',
      signupIntro: 'اطلاعات خود را وارد کنید',
      signupFooter: 'شروع استفاده از پلتفرم نوبت‌دهی آنلاین',
      signupFooterSub: 'ثبت نام سریع و رایگان',
      roleCustomerDesc: 'رزرو نوبت آنلاین',
      roleOwnerDesc: 'مدیریت سالن و نوبت‌ها',
      genderLabel: 'جنسیت',
      genderMale: 'مرد',
      genderFemale: 'زن',
      selectCity: 'انتخاب شهر',
      cityModalTitle: 'انتخاب شهر',
      citySearchPlaceholder: 'جستجو...',
      cityNotFound: 'شهری یافت نشد',
      showPassword: 'نمایش رمز عبور',
      hidePassword: 'مخفی کردن رمز عبور',
      usernamePlaceholder: 'نام کاربری',
      emailPlaceholder: 'example@email.com',
      firstNamePlaceholder: 'نام',
      lastNamePlaceholder: 'نام خانوادگی',
      phonePlaceholder: '۰۹۱۲۳۴۵۶۷۸۹',
      cityPlaceholder: 'انتخاب شهر',
      salonNamePlaceholder: 'نام سالن',
      salonCityPlaceholder: 'شهر سالن',
      salonPhonePlaceholder: 'شماره تلفن سالن',
      salonAddressPlaceholder: 'آدرس کامل سالن',
      passwordPlaceholder: 'رمز عبور',
      passwordConfirmPlaceholder: 'تأیید رمز عبور',
      fieldRequired: 'این فیلد الزامی است',
      usernameRequired: 'نام کاربری الزامی است',
      usernameMin: 'حداقل ۳ کاراکتر',
      usernameAscii: 'فقط حروف و ارقام انگلیسی',
      emailRequired: 'ایمیل الزامی است',
      emailInvalid: 'ایمیل معتبر نیست (مثال: user@example.com)',
      passwordRequired: 'رمز عبور الزامی است',
      passwordMin: 'رمز عبور باید حداقل ۶ کاراکتر باشد',
      passwordConfirmRequired: 'تأیید رمز عبور الزامی است',
      passwordsMismatch: 'رمزها مطابقت ندارند',
      phoneRequired: 'شماره تلفن الزامی است',
      phoneInvalid: 'شماره تلفن باید حداقل ۱۰ رقم باشد',
      cityRequired: 'شهر الزامی است',
      salonNameRequired: 'نام سالن برای مالک الزامی است',
      salonCityRequired: 'شهر سالن برای مالک الزامی است',
      salonGenderRequired: 'جنسیت سالن برای مالک الزامی است',
      salonAddressRequired: 'آدرس سالن برای مالک الزامی است',
      salonPhoneInvalid: 'شماره سالن معتبر نیست (حداقل ۱۰ رقم)',
      generalError: 'لطفاً خطاهای مشخص‌شده را اصلاح کنید',
      success: 'ثبت‌نام با موفقیت انجام شد',
    },
    resetPassword: {
      title: 'تعیین رمز عبور جدید',
      subtitle: 'رمز عبور تازه را برای حساب خود انتخاب کنید',
      newPassword: 'رمز عبور جدید',
      confirmPassword: 'تکرار رمز عبور',
      submit: 'تغییر رمز عبور',
      loading: 'در حال تغییر رمز عبور...',
      successRedirect: 'در حال انتقال به صفحه ورود...',
      passwordRequired: 'رمز عبور جدید را وارد کنید',
      confirmRequired: 'تکرار رمز عبور را وارد کنید',
      mismatch: 'رمزهای عبور با هم مطابقت ندارند',
      networkError: 'خطای شبکه. لطفاً دوباره تلاش کنید.',
      invalidLink: 'لینک بازیابی نامعتبر است.'
    },
    home: {
      heroTitle: 'رزرو آنلاین خدمات آرایشگاه',
      heroSubtitle: 'سرویس مورد نظر را انتخاب کنید و زمان دلخواه را رزرو کنید',
      sectionTitle: 'چند کلیک تا رزرو نوبت',
      sectionSubtitle: 'فقط چند کلیک فاصله دارید تا نوبت خود را ثبت کنید',
      sectionTitleOwner: 'تجربه‌ای متفاوت در نوبت‌دهی',
      sectionSubtitleOwner: 'ابزارهای حرفه‌ای برای مدیریت سریع و مطمئن سالن',
      howItWorksTitle: 'چطور کار می‌کند؟',
      howItWorksSubtitle: 'در سه قدم ساده نوبت خود را رزرو کنید',
      howItWorksDesc: 'از جستجو تا رزرو، تنها چند کلیک فاصله دارید',
      howItWorksStep1Title: 'آرایشگاه را پیدا کنید',
      howItWorksStep1Desc: 'با جستجو بر اساس نام یا شهر، آرایشگاه مورد نظرتان را در پلتفرم پیدا کنید',
      howItWorksStep2Title: 'خدمت را انتخاب کنید',
      howItWorksStep2Desc: 'لیست خدمات، قیمت و مدت‌زمان هر کدام را ببینید و خدمت مدنظرتان را انتخاب کنید',
      howItWorksStep3Title: 'نوبت بگیرید',
      howItWorksStep3Desc: 'زمان مناسب خودتان را انتخاب کنید و نوبت‌تان ثبت می‌شود؛ همین‌قدر ساده',
      whoForTitle: 'برای چه کسانی مناسب است؟',
      whoForSubtitle: 'هم برای مشتری، هم برای صاحب سالن',
      customerFeatureTitle: 'آرایشگاه مناسب خودت رو پیدا کن',
      customerFeatureDesc: 'جستجو کن، نوبت بگیر و بدون انتظار برو آرایشگاه!',
      customerBookingTitle: 'نوبتت رو آنلاین بگیر',
      customerBookingDesc: 'خدمت دلخواه، قیمت و زمان مناسب رو انتخاب کن — نوبت در چند ثانیه ثبت میشه',
      customerBestTitle: 'بهترین‌ها رو انتخاب کن',
      customerBestDesc: 'امتیاز و نظرات مشتریان قبلی کمکت می‌کنه بهترین آرایشگاه رو با اطمینان انتخاب کنی',
      ownerFeatureTitle: 'مدیریت هوشمند نوبت‌ها',
      ownerFeatureDesc: 'کنترل کامل رزروها و برنامه‌ریزی دقیق کاری در هر ساعت از شبانه‌روز',
      ownerVisibilityTitle: 'دیده شدن در برترین‌ها',
      ownerVisibilityDesc: 'نمایش حرفه‌ای سالن شما در کنار بهترین‌های شهر، جهت جذب مشتریان جدید و معتبر',
      ownerOptimizationTitle: 'بهینه‌سازی زمان و درآمد',
      ownerOptimizationDesc: 'کاهش کنسلی‌ها و مدیریت دقیق زمان‌بندی برای افزایش بهره‌وری و درآمد سالن',
      ownerPanelTitleText: 'پنل مدیریت حرفه‌ای',
      ownerPanelDesc: 'ابزارهای گزارش‌گیری و تیم پشتیبانی اختصاصی برای مدیریت ساده و سریع کسب‌وکارتان',
      welcomeTitle: 'به سالنیفای خوش آمدید',
      dashboardTitle: 'میز مانیتورینگ و وضعیت سالن',
      dashboardSubtitle: 'ابزارهای حیاتی کاربری و تحلیل آماری زنده بر اساس وضعیت واقعی سیستم شما.',
      bookingLinkTitle: 'لینک اختصاصی نوبت‌دهی',
      bookingLinkDesc: 'این لینک اختصاصی سالن شماست. آن را کپی کرده و در بیو اینستاگرام، پیامک‌ها یا کانال‌های ارتباطی خود قرار دهید تا مشتریان مستقیماً نوبت بگیرند.',
      bookingLinkButton: 'کپی کردن لینک نوبت‌دهی',
      bookingLinkCopied: 'لینک با موفقیت کپی شد!',
      servicesSummaryTitle: 'وضعیت خدمات و قیمت‌ها',
      activeServicesLabel: 'خدمات فعال برای مشتریان:',
      inactiveServicesLabel: 'خدمات غیرفعال موقت:',
      averagePriceLabel: 'میانگین ارزش خدمات سالن:',
      totalServicesLabel: 'تعداد کل خدمات تعریف شده:',
      salonIdentityTitle: 'شناسنامه دیجیتال سالن',
      salonIdentityDesc: 'خلاصه‌ای از ساختار و مشخصاتی که مشتریان شما در پروفایل نوبت‌دهی خود مشاهده می‌کنند. اطلاعات تکمیلی در تب تنظیمات قابل ویرایش است.',
      salonCityLabel: 'شهر فعالیت ثبت‌شده:',
      salonGenderLabel: 'تخصص جنسیتی سالن:',
      salonRatingLabel: 'میانگین امتیاز مشتریان:',
      salonPhoneLabel: 'تلفن تماس:',
      topSalonsTitle: 'برترین آرایشگاه‌ها',
      topSalonsSubtitle: '۵ آرایشگاه برتر که مشتریان بیشترین رضایت را داشته‌اند',
      viewAllTitle: 'آرایشگاه بیشتری می‌خوای پیدا کنی؟',
      viewAllSubtitle: 'در صفحه آرایشگاه‌ها می‌تونی با فیلتر شهر، جنسیت و جستجو، دقیقاً همون رو که می‌خوای پیدا کنی',
      viewAllButton: 'مشاهده همه آرایشگاه‌ها',
      moreSalonsLabel: '{count}+ آرایشگاه در پلتفرم',
      moreSalonsText: 'آرایشگاه‌های بیشتری در راه است',
      platformTitle: 'اعتماد کاربران به پلتفرم ما در یک نگاه',
      platformSubtitle: 'با پلتفرم ما تجربه‌ای سریع، مطمئن و راحت از نوبت‌دهی آنلاین داشته باشید',
      platformSalons: 'آرایشگاه همکار',
      platformBookings: 'نوبت موفق',
      platformSatisfaction: 'رضایت کاربران',
      noSalonsTitle: 'هنوز آرایشگاهی ثبت نشده',
      noSalonsText: 'به زودی آرایشگاه‌های جدید اضافه می‌شوند',
      welcomeSubtitle: 'پلتفرمی برای نوبت‌دهی آنلاین آرایشگاه‌ها؛ آرایشگاه مورد نظرتان را پیدا کنید، خدمت دلخواه را انتخاب کنید و در چند ثانیه نوبت بگیرید',
      welcomeSubtitle2: 'بدون نیاز به تماس تلفنی یا حضور حضوری، آرایشگاه‌های ثبت‌شده در پلتفرم را مرور کنید و نوبت خودتان را مدیریت کنید. صاحبان سالن نیز می‌توانند خدمات و نوبت‌های خود را از طریق پنل مدیریتی کنترل کنند.',
      startFree: 'شروع کنید — رایگان',
      loginAccount: 'ورود به حساب',
      freeSignup: 'ثبت‌نام رایگان',
      customerSignup: 'ثبت‌نام به‌عنوان مشتری',
      ownerSignup: 'ثبت‌نام به‌عنوان صاحب سالن',
      customerSearchHint: 'جستجوی آرایشگاه‌های ثبت‌شده در پلتفرم بر اساس نام یا شهر',
      customerPriceHint: 'مشاهده دقیق قیمت و مدت‌زمان هر خدمت پیش از رزرو',
      customerBookingHint: 'رزرو و مدیریت نوبت‌ها از طریق حساب کاربری شخصی',
      ownerServicesHint: 'تعریف و مدیریت خدمات سالن همراه با قیمت و مدت‌زمان',
      ownerBookingsHint: 'مشاهده و مدیریت نوبت‌های ثبت‌شده توسط مشتریان',
      ownerVisibilityHint: 'معرفی سالن به مشتریان جدید از طریق پلتفرم',
      noAppRequired: 'بدون نیاز به نصب اپلیکیشن',
      bookAnyTime: 'رزرو در هر ساعت از شبانه‌روز',
      searchTitle: 'جستجوی آرایشگاه',
      searchSubtitle: 'نام آرایشگاه را جستجو کنید',
      searchPlaceholder: 'نام آرایشگاه را جستجو کنید...',
      searchEmpty: 'آرایشگاهی یافت نشد',
      searchEmptyHint: 'آرایشگاهی با این نام یافت نشد',
      searchHint: 'نام آرایشگاه را جستجو کنید',
      salonCount: 'آرایشگاه',
      salonsCountPlural: 'آرایشگاه',
      bookNow: 'رزرو کنید',
      viewServices: 'مشاهده خدمات',
      openHours: 'ساعات کاری',
      contact: 'تماس',
      services: 'خدمات',
      ourServices: 'خدمات ما',
      popularSalons: 'آرایشگاه‌های محبوب',
      about: 'درباره ما',
      aboutText: 'پلتفرم رزرو آنلاین برای دسترسی سریع و راحت به خدمات آرایشگاه‌ها',
      joinNow: 'همین حالا شروع کنید',
      ownerPanelTitle: 'پنل حرفه‌ای مدیریت سالن',
      ownerPanelHeading: 'مدیریت سالن',
      ownerPanelIntro: 'سلام {name}؛ به پیشخوان مدیریت سالن خود خوش آمدید. نوبت‌ها و خدمات خود را با ابزارهای زیر بهینه‌سازی کنید.',
      ownerHeroTitle: 'صاحبان سالن',
      ownerHeroPoint1: 'تعریف و مدیریت خدمات سالن همراه با قیمت و مدت‌زمان',
      ownerHeroPoint2: 'مشاهده و مدیریت نوبت‌های ثبت‌شده توسط مشتریان',
      ownerHeroPoint3: 'معرفی سالن به مشتریان جدید از طریق پلتفرم',
      ownerHeroButton: 'ثبت‌نام سالن من',
      salonGenderMale: '♂ تخصصی آقایان',
      salonGenderFemale: '♀ تخصصی بانوان',
      noRating: 'بدون امتیاز',
      notProvided: 'ثبت نشده',
      customerGreeting: 'خوش اومدی',
      customerFallback: 'مشتری گرامی',
      ownerFallback: 'مدیر گرامی',
      customerHeading: 'بهترین آرایشگاه را پیدا کن ✨',
      customerHeadingGender: 'بهترین آرایشگاه‌های {gender} را پیدا کن ✨',
      customerPromo: 'جستجو کن، نوبت بگیر و بدون انتظار برو آرایشگاه!',
      customerPromoGender: 'جستجو کن، نوبت بگیر و فقط سالن‌های {gender} را ببین!',
      whyTitle: 'چرا سالنیفای؟',
      whyCustomer: 'بدون تماس تلفنی، بدون انتظار — فقط رزرو کن و برو',
      whyOwner: 'همه چیز را در یک پلتفرم مدیریت کنید',
      featureSearchDesc: 'از بین آرایشگاه‌های ثبت‌شده در شهرت جستجو کن، امتیاز و نظرات رو ببین و انتخاب کن',
      featureTimingTitle: 'بدون انتظار، سر وقت برو',
      featureTimingDesc: 'خدمات و نوبت‌ها را سریع و بدون معطلی از طریق پلتفرم رزرو کن',
      ownerSummary: 'خلاصه‌ای از خدمات فعال شما در سامانه نوبت‌دهی سالنیفای به همراه برآورد ارزش و میانگین قیمت واقعی تراکنش‌های سالن شما.',
      close: 'بستن',
      applyFilter: 'اعمال فیلتر',
      selectCity: 'انتخاب شهر',
      selectCitySubtitle: 'شهر مورد نظر خود را انتخاب کنید',
      allCities: 'همه شهرها',
      noSalonsFound: 'آرایشگاهی یافت نشد',
      noSalonsFoundHint: 'آرایشگاهی با این نام یافت نشد',
      searchByName: 'نام آرایشگاه را جستجو کنید',
      resultsCount: '{count} آرایشگاه',
      serviceSingular: 'خدمت',
      servicePlural: 'خدمت',
      itemSingular: 'مورد',
      itemPlural: 'مورد',
      reviewSingular: 'نظر',
      reviewPlural: 'نظر',
      loadError: 'بارگذاری اطلاعات سالن ناموفق بود.',
      salonsLoadError: 'بارگذاری لیست سالن‌ها ناموفق بود.'
    },
    salons: {
      title: 'آرایشگاه‌های سالنیفای',
      subtitle: 'از میان {count} آرایشگاه در شهر شما انتخاب کنید',
      back: 'بازگشت',
      searchPlaceholder: 'جستجوی نام آرایشگاه یا شهر...',
      genderBadge: 'فقط آرایشگاه‌های {gender} نمایش داده می‌شود',
      cityBadge: 'فقط آرایشگاه‌های شهر شما نمایش داده می‌شود',
      forYouBadge: 'مخصوص شما',
      filterAll: 'همه',
      clearFilters: 'پاک کردن فیلترها',
      countLabel: 'آرایشگاه',
      smartSortBanner: 'نتایج بر اساس موقعیت، امتیاز و محبوبیت مرتب شده‌اند',
      emptyFiltersHint: 'فیلترها را تغییر دهید یا پاک کنید',
      sortTitle: 'مرتب‌سازی',
      sortSubtitle: 'نحوه نمایش آرایشگاه‌ها را انتخاب کنید',
      sortSmart: 'پیشنهاد هوشمند',
      sortSmartDesc: 'بر اساس موقعیت، امتیاز و نظرات',
      sortRating: 'بالاترین امتیاز',
      sortRatingDesc: 'آرایشگاه‌های با بیشترین ستاره',
      sortNewest: 'جدیدترین',
      sortNewestDesc: 'تازه‌ترین آرایشگاه‌های عضو',
      sortReviews: 'بیشترین نظرات',
      sortReviewsDesc: 'محبوب‌ترین در میان مشتریان',
      sortName: 'نام (الفبا)',
      sortNameDesc: 'مرتب‌سازی حروف الفبا',
    },
    services: {
      heroTitle: 'خدمات سالن',
      heroSubtitle: 'خدمت مورد نظر را انتخاب و نوبت بگیرید',
      genderMale: 'مردانه',
      genderFemale: 'زنانه',
      activeServices: 'خدمت فعال',
      activeServicesPlural: 'خدمت فعال',
      disabledTitle: 'سالن در حال حاضر غیرفعال است',
      disabledText: 'تا اطلاع ثانوی غیرفعال است.',
      priceNote: 'قیمت‌های نمایش داده‌شده پایه هستند و ممکن است بر اساس درخواست شما تغییر کنند.',
      aboutOwner: 'متخصص آرایش',
      address: 'آدرس',
      phone: 'تلفن',
      openHours: 'ساعات کاری',
      noServices: 'خدمتی در دسترس نیست',
      book: 'رزرو این خدمت',
      loading: 'در حال بارگذاری خدمات...',
      serviceList: 'لیست خدمات',
      salonInfo: 'اطلاعات سالن',
      bookNow: 'رزرو نوبت',
    },
    booking: {
      title: 'رزرو نوبت',
      subtitle: 'تاریخ و زمان مناسب خود را انتخاب کنید',
      selectDate: 'انتخاب تاریخ',
      selectTime: 'انتخاب زمان',
      continue: 'ادامه',
      confirm: 'تأیید رزرو',
      success: 'رزرو با موفقیت انجام شد',
      error: 'رزرو انجام نشد. لطفاً دوباره تلاش کنید.',
      loading: 'در حال بارگذاری...',
      service: 'خدمت',
      salon: 'آرایشگاه',
      price: 'قیمت',
      time: 'زمان',
      date: 'تاریخ',
      customerName: 'نام مشتری',
      phone: 'شماره تماس',
      email: 'ایمیل',
      notes: 'توضیحات',
      back: 'بازگشت',
      noSalonSelectedTitle: 'سالن انتخاب نشده',
      noSalonSelectedMessage: 'لطفاً ابتدا یک سالن را از صفحه خانه انتخاب کنید تا بتوانید نوبت رزرو کنید.',
      goHome: 'رفتن به صفحه خانه',
      tryAgain: 'تلاش مجدد',
      goBack: 'بازگشت',
      calendarErrorTitle: 'خطا در بارگذاری تقویم',
      calendarErrorMessage: 'دریافت تاریخ‌های در دسترس با مشکل مواجه شد. لطفاً اتصال اینترنت خود را بررسی کرده و دوباره تلاش کنید.',
      selected: 'انتخاب‌شده',
      today: 'امروز',
      full: 'کامل',
      closed: 'تعطیل',
      fullDayBooked: 'تمام نوبت‌های این روز رزرو شده است',
      salonClosedToday: 'سالن در این روز تعطیل است',
    },
    bookings: {
      title: 'نوبت‌های من',
      subtitle: 'وضعیت رزروهای شما',
      empty: 'هنوز نوبتی ثبت نکرده‌اید',
      loading: 'در حال بارگذاری رزروها...',
      service: 'خدمت',
      time: 'زمان',
      status: 'وضعیت',
      cancel: 'لغو',
      confirm: 'تأیید',
      noBookings: 'رزروی برای نمایش وجود ندارد',
      accountInfoTitle: 'اطلاعات حساب کاربری',
      accountInfoUsername: 'نام کاربر',
      accountInfoPhone: 'شماره موبایل',
      accountInfoEmail: 'ایمیل',
      bookingsListTitle: 'لیست رزروها',
      searchTitle: 'جستجوی نوبت‌ها',
      searchPhone: 'شماره موبایل',
      searchPlaceholder: 'مثال: ۰۹۱۲۱۲۳۴۵۶۷',
      searchButton: 'جستجوی نوبت‌ها',
      searchLoading: 'در حال جستجو...',
      searchHint: 'برای دسترسی ساده‌تر و مشاهده تمامی نوبت‌ها، وارد حساب کاربری خود شوید.',
      loadingBookings: 'در حال بارگذاری نوبت‌ها...',
      totalBookings: 'کل نوبت‌ها',
      confirmedStatus: 'تأیید شده',
      pendingStatus: 'در انتظار',
      cancelledStatus: 'لغو شده',
      noBookingsFoundTitle: 'نوبتی یافت نشد',
      noBookingsFoundHint: 'برای مشاهده نوبت‌های خود، شماره موبایل خود را وارد کنید.',
      noBookingsFoundEmpty: 'شما هنوز نوبتی ثبت نکرده‌اید یا نوبتی با این مشخصات وجود ندارد.',
      bookingNotCancellable: 'این نوبت دیگر قابل لغو نیست.',
      cancelConfirmTitle: 'تأیید لغو نوبت',
      cancelConfirmText: 'مطمئنی که می‌خواهی این نوبت را لغو کنی؟',
      cancelConfirmDetail: 'این عملیات قابل بازگشت نیست. در صورت لغو، نوبت مربوط به {service} حذف می‌شود.',
      cancelConfirmHint: 'برای ادامه، دکمه بله، لغو شود را بزن. اگر منصرف شدی، می‌توانی این پنجره را ببندی.',
      cancelConfirmCancel: 'انصراف',
      cancelConfirmSubmit: 'بله، لغو شود',
      cancelConfirmSubmitting: 'در حال لغو...',
      successTitle: 'عملیات موفق',
      successConfirm: 'رزرو با موفقیت تأیید شد.',
      successCancel: 'نوبت با موفقیت لغو شد.',
      goHome: 'بازگشت به صفحه اصلی',
      noSalonSelectedTitle: 'سالن انتخاب نشده',
      noSalonSelectedText: 'لطفاً ابتدا از صفحه اصلی یک سالن را انتخاب کنید.',
      confirmBookingAction: 'تأیید رزرو',
      cancelBookingAction: 'لغو رزرو',
      cancelCustomerBooking: 'لغو نوبت',
      bookingStarted: 'شروع شده',
      daysLabel: 'روز',
      hoursLabel: 'ساعت',
      minutesLabel: 'دقیقه',
      unknownStatus: 'نامشخص',
    },
    ownerBookings: {
      title: 'مدیریت رزروها',
      subtitle: 'مشاهده و مدیریت رزروهای سالن',
      back: 'بازگشت به پنل',
      salonInfo: 'اطلاعات سالن',
      salonName: 'نام سالن',
      city: 'شهر',
      phone: 'تلفن',
      bookingsList: 'لیست رزروها',
      loading: 'در حال بارگذاری رزروها...',
      salonNameLabel: 'نام سالن',
      cityLabel: 'شهر',
      phoneLabel: 'تلفن',
    },
    admin: {
      title: 'پنل مدیریت سالن',
      overview: 'خلاصه آماری',
      services: 'خدمات',
      addService: 'افزودن خدمت',
      addServiceTitle: 'نام خدمت',
      addServicePrice: 'قیمت خدمت',
      addServiceDuration: 'مدت زمان',
      addServiceCategory: 'دسته‌بندی',
      addServiceSubmit: 'ثبت خدمت',
      workingHours: 'ساعات کاری',
      bookings: 'رزروها',
      reviews: 'نظرات مشتریان',
      portfolio: 'نمونه کارها',
      ownerInfo: 'مشخصات مالک',
      qrCode: 'QR کد سالن',
      settings: 'تنظیمات سالن',
      filterAll: 'همه',
      filterPending: 'در انتظار تأیید',
      filterConfirmed: 'تأیید شده',
      filterCancelled: 'لغو شده',
      serviceNameRequired: 'لطفاً نام خدمت را وارد کنید',
      servicePriceRequired: 'قیمت این سرویس باید بیشتر از صفر باشد',
      serviceDuplicate: 'خدمت تکراری',
      serviceAddError: 'خطا در اضافه کردن خدمت',
      serviceUpdateError: 'خطا در بروزرسانی خدمت',
      serviceEnableSuccess: 'خدمت فعال شد. اکنون برای مشتریان نمایش داده می‌شود.',
      serviceDisableSuccess: 'خدمت غیرفعال شد. دیگر برای مشتریان نمایش داده نمی‌شود.',
      serviceNameLabel: 'نام خدمت',
      servicePriceLabel: 'قیمت خدمت',
      serviceDurationLabel: 'مدت زمان (دقیقه)',
      serviceNamePlaceholder: 'مثال: کوتاه کردن مو',
      servicePricePlaceholder: 'مثال: 500000',
      serviceDurationPlaceholder: 'مثال: 30',
      workingHourSelectDay: 'لطفاً یک روز را انتخاب کنید',
      workingHourSelectShift: 'لطفاً حداقل یک شیفت اضافه کنید',
      workingHourMaxShifts: 'حداکثر ۲ شیفت برای هر روز مجاز است',
      workingHourTimeOrder: 'ساعت شروع باید قبل از ساعت پایان باشد',
      workingHourSaveSuccessNext: 'روز {day} ذخیره شد. حالا {nextDay} را تنظیم کن.',
      workingHourSaveSuccessEnd: 'ساعات کاری {day} با موفقیت ذخیره شد',
      workingHourDeleteError: 'خطا در حذف ساعات کاری',
      workingHourDeleteConfirmTitle: 'حذف شیفت کاری',
      workingHourDeleteConfirmMessage: 'آیا مطمئنی که می‌خواهی این شیفت رو حذف کنی؟',
      activeDaysLabel: 'روزهای فعال',
      totalShiftsLabel: 'کل شیفت‌ها',
      multiShiftDaysLabel: 'روزهای چندشیفته',
      salonInfoTitle: 'اطلاعات سالن',
      salonNameLabel: 'نام سالن',
      cityLabel: 'شهر',
      phoneLabel: 'تلفن',
      mobileLabel: 'موبایل',
      addressLabel: 'آدرس',
      contactEditButton: 'ویرایش شماره تلفن و موبایل',
      contactPhoneLabel: 'تلفن ثابت (اختیاری)',
      contactPhonePlaceholder: 'مثلاً 02112345678',
      contactMobileLabel: 'موبایل (الزامی)',
      salonStatusTitle: 'وضعیت سالن',
      salonDisabledStatus: 'سالن در حال حاضر غیرفعال است',
      salonDisabledUntil: 'تا {date}',
      salonActiveStatus: 'سالن فعال است',
      activateSalonButton: 'فعال کردن سالن',
      deactivateSalonButton: 'غیرفعال کردن سالن',
      disableSalonTitle: 'غیرفعال کردن سالن',
      disableSalonDurationLabel: 'مدت زمان غیرفعال بودن (روز) - اختیاری',
      disableSalonDurationPlaceholder: 'مثال: 7 (برای یک هفته)',
      disableSalonDurationHint: 'اگر خالی بگذارید، سالن تا زمانی که خودتان فعال نکنید غیرفعال می‌ماند',
      disableSalonReasonLabel: 'دلیل غیرفعال کردن - اختیاری',
      disableSalonReasonPlaceholder: 'مثال: تعطیلات، نوسازی...',
      disableSalonSubmit: 'غیرفعال کردن',
      disableSalonCancel: 'انصراف',
      disableSalonProcessing: 'در حال پردازش...',
      ownerSavingState: 'در حال ذخیره‌سازی...',
      ownerSaveButton: 'ذخیره مشخصات',
      ownerContactSaveButton: 'ذخیره',
      ownerContactCancelButton: 'انصراف',
      workingHoursStatusActive: 'فعال',
      workingHoursStatusRest: 'استراحت',
      workingHoursShiftCount: '{count} شیفت',
      contactMobilePlaceholder: 'مثلاً 09123456789',
      contactSaveButton: 'ذخیره',
      contactCancelButton: 'انصراف',
      contactMobileRequiredTitle: 'شماره موبایل الزامی است',
      contactMobileRequiredMessage: 'برای ذخیره اطلاعات، وارد کردن شماره موبایل الزامی است.',
      contactSaveSuccess: 'شماره‌های تماس با موفقیت ذخیره شد',
      contactSaveErrorTitle: 'خطا در ذخیره شماره تماس',
      ownerInfoDescriptionTooLong: 'توضیح درباره خود نباید بیشتر از ۵۰۰ کاراکتر باشد.',
      ownerInfoRequired: 'لطفا حداقل یک مورد (عکس یا توضیح) را وارد کنید.',
      ownerInfoSaveSuccess: 'مشخصات مالک با موفقیت ذخیره شد',
      ownerInfoSaveErrorTitle: 'خطا در ذخیره مشخصات',
      ownerInfoSaveErrorMessage: 'خطا در ذخیره اطلاعات مالک',
      imageSizeError: 'سایز عکس نباید از 5 مگابایت بیشتر باشد',
      imageTypeError: 'فقط عکس های JPEG, PNG, WebP و GIF پذیرفتنی هستند',
      errorTitle: 'خطا',
      successTitle: 'موفق',
      noDataTitle: 'درحال بارگذاری...',
      qrDownloadButton: 'دانلود',
      qrPrintButton: 'چاپ',
      qrIdLabel: 'شناسه QR Code:',
      qrLinkLabel: 'لینک QR Code:',
      qrHowToUseTitle: '🎯 نحوه استفاده:',
      qrHowToUseStep1: 'تصویر QR کد را دانلود کنید',
      qrHowToUseStep2: 'آن را چاپ کرده و در مغازه قرار دهید',
      qrHowToUseStep3: 'مشتریان با دوربین گوشی اسکن می‌کنند',
      qrHowToUseStep4: 'صفحه سالن شما باز می‌شود',
      qrHowToUseStep5: 'مشتری نوبت رزرو می‌کند',
      qrPrintTitle: 'چاپ QR Code',
      qrScanHint: 'برای رزرو نوبت اسکن کنید',
      qrLoadingText: 'درحال بارگذاری...',
      positionEditorVertical: 'عمودی (بالا/پایین)',
      positionEditorReset: 'بازنشانی مرکز',
      positionEditorConfirm: 'تأیید موقعیت ✓',
      bookingTableCustomer: 'مشتری',
      bookingTableService: 'خدمت',
      bookingTableDateTime: 'تاریخ و ساعت',
      bookingTableStatus: 'وضعیت',
      bookingTableContact: 'اطلاعات تماس',
      noWorkingHoursForDay: 'برای این روز هنوز شیفتی ثبت نشده است.',
      qrCodeErrorOwner: 'فقط مالک سالن می‌تواند QR Code را ببیند',
      qrCodeErrorAuth: 'لطفاً وارد حساب کاربری خود شوید',
      qrCodeErrorGeneric: 'خطا در دریافت QR Code',
      salonLoadError: 'خطا در بارگذاری اطلاعات',
      servicePriceHint: 'برای فعال‌سازی این سرویس، ابتدا قیمت آن را بیشتر از صفر وارد کنید.',
      accessDenied: 'دسترسی رد شد. فقط مالک و کارمند می‌توانند وارد شوند.',
      welcomeUser: 'خوش آمدید، {username}',
      manageServicesTitle: 'مدیریت خدمات',
      manageServicesSubtitle: 'خدمات سالن رو ببین، ویرایش کن یا فعال/غیرفعال کن.',
      manageServicesAddButton: 'خدمت جدید',
      manageServicesAddModalTitle: 'افزودن خدمت جدید',
      manageServicesEditModalTitle: 'ویرایش خدمت',
      manageServicesSave: 'ذخیره خدمت',
      manageServicesUpdate: 'ذخیره تغییرات',
      manageServicesEmptyTitle: 'هنوز خدمتی ثبت نشده است',
      manageServicesEmptySubtitle: 'برای شروع، خدمت جدیدی اضافه کنید',
      manageServicesInfoTitle: 'وقتی روی دکمه فعال/غیرفعال کلیک کنید:',
      manageServicesInfoActive: 'اگر خدمت فعال است: برای مشتریان نمایش داده می‌شود و می‌توانند نوبت بگیرند',
      manageServicesInfoInactive: 'اگر خدمت غیرفعال است: برای مشتریان نمایش داده نمی‌شود و نمی‌توانند نوبت بگیرند',
      manageServicesInfoNoDelete: 'خدمت حذف نمی‌شود - فقط وضعیتش تغییر می‌کند',
      manageServicesCancel: 'انصراف',
      manageServicesSaving: 'در حال ذخیره...',
      workingHoursTitle: 'مدیریت ساعات کاری',
      workingHoursSubtitle: 'روزها را کارت‌محور ببین، شیفت‌ها را با drag & drop بچین و فقط با یک لمس روی چند روز اعمال کن.',
      workingHoursAddButton: 'افزودن زمان‌بندی',
      workingHoursCloseButton: 'بستن',
      workingHoursFormTitle: 'تنظیم روز به روز ساعات کاری',
      workingHoursFormSubtitle: 'هر روز را جداگانه تنظیم کن، ذخیره کن و با دکمه روز بعدی برو سراغ روز بعدی. پنج‌شنبه و جمعه هم می‌توانند ساعت متفاوت داشته باشند.',
      workingHoursCurrentDay: 'روز فعلی',
      workingHoursPrevDay: 'قبلی',
      workingHoursNextDay: 'روز بعدی',
      workingHoursSavedStatus: 'ثبت شده',
      workingHoursFreeStatus: 'آزاد',
      workingHoursPresetReady: 'preset آماده برای همین روز',
      workingHoursResetDay: 'بازنشانی شیفت‌های روز',
      workingHoursResetCurrent: 'بازنشانی روز فعلی',
      workingHoursAddShift: '+ افزودن شیفت دوم',
      workingHoursMaxShifts: 'حداکثر ۲ شیفت در هر روز',
      workingHoursSaveAndNext: 'ثبت این روز و رفتن به {nextDay}',
      workingHoursSaveAndEnd: 'ثبت و پایان',
      workingHoursSaveCurrentDay: 'هر بار فقط همان روزی که بالای فرم انتخاب شده ذخیره می‌شود. بعد از ذخیره، به روز بعدی می‌رویم.',
      bookingsTitle: 'مدیریت رزروها',
      bookingsEmptyTitle: 'هنوز رزروی ثبت نشده است',
      bookingsEmptySubtitle: 'مشتریان هنوز نوبت‌گیری نکرده‌اند',
      bookingsFilterLabel: 'فیلتر وضعیت',
      bookingsCountLabel: '{count} رزرو',
      bookingsNoMatchTitle: 'هیچ رزروی با این وضعیت وجود ندارد',
      reviewsTitle: 'نظرات مشتریان',
      portfolioTitle: 'مدیریت نمونه کارها',
      ownerInfoTitle: 'مشخصات مالک',
      qrCodeTitle: 'QR کد سالن',
      settingsTitle: 'تنظیمات سالن',
      ownerInfoSectionTitle: 'اطلاعات سالن',
      ownerPreviewLabel: 'پیش‌نمایش نهایی',
      ownerPositionButton: 'تنظیم موقعیت',
      ownerPositionHelpTitle: 'موقعیت عکس را تنظیم کنید',
      ownerPositionHelpText: 'عکس را در کادر زیر بکشید تا بهترین قاب دایره‌ای رو انتخاب کنید',
      ownerPositionReset: 'بازنشانی مرکز',
      ownerPositionConfirm: 'تأیید موقعیت ✓',
      ownerImageSelectLabel: 'عکس را انتخاب کنید',
      ownerImageChangeLabel: 'تغییر عکس',
      ownerImageLabel: 'عکس مالک (دایره‌ای)',
      ownerImageHint: 'JPEG, PNG, WebP یا GIF (حداکثر 5 مگابایت)',
      ownerDescriptionLabel: 'توضیح درباره خود (حداکثر ۵۰۰ کاراکتر)',
      ownerDescriptionPlaceholder: 'درباره خود و تخصص‌های خود را بنویسید...',
      ownerDescriptionCount: '{count} / ۵۰۰ کاراکتر',
      ownerAccessDenied: 'QR Code فقط برای مالک سالن قابل مشاهده است',
      workingHoursShiftLabel: 'شیفت {number}',
      workingHoursDeleteButton: 'حذف',
      workingHoursMoveButton: 'جابه‌جایی',
      workingHoursStartTimeLabel: 'ساعت شروع',
      workingHoursEndTimeLabel: 'ساعت پایان',
      workingHoursNextDayHint: 'بعدی: {day}',
      workingHoursLastDayHint: 'آخرین روز هفته',
      workingHoursDaySummary: 'تنها این روز ذخیره می‌شود',
      workingHoursStatusLabel: 'وضعیت',
      workingHoursNoShiftsBadge: 'تعطیل',
      workingHoursDeleteConfirmationTitle: 'حذف شیفت',
      workingHoursDeleteConfirmationMessage: 'آیا از حذف این شیفت مطمئن هستید؟',
      workingHoursDeleteConfirmationCancel: 'انصراف',
      workingHoursDeleteConfirmationSubmit: 'بله، حذف شود',
      weekDay0: 'شنبه',
      weekDay1: 'یکشنبه',
      weekDay2: 'دوشنبه',
      weekDay3: 'سه‌شنبه',
      weekDay4: 'چهارشنبه',
      weekDay5: 'پنج‌شنبه',
      weekDay6: 'جمعه',
      presetMorning: 'صبح کاری',
      presetAfternoon: 'بعدازظهر',
      presetSplit: 'صبح / عصر',
      presetFull: 'تمام روز'
    },
    portfolioManager: {
      title: 'مدیریت نمونه کارها',
      newCategory: 'دسته‌بندی جدید',
      categoryCount: '{count}/{max}',
      addCategory: 'افزودن دسته‌بندی',
      addCategoryLoading: 'در حال ایجاد...',
      categoryName: 'نام دسته‌بندی',
      categoryDescription: 'توضیح',
      uploadTitle: 'عنوان عکس',
      uploadDescription: 'توضیح',
      uploadHint: 'کلیک کنید یا فایل را اینجا بکشید',
      uploadError: 'خطا در بارگذاری',
      deleteCategory: 'حذف دسته',
      deleteItem: 'حذف عکس',
      noCategories: 'هیچ دسته‌بندی وجود ندارد',
      noCategoriesHint: 'ابتدا یک دسته‌بندی بسازید و سپس عکس اضافه کنید',
      noItems: 'هنوز عکسی اضافه نشده',
      noItemsHint: 'از فرم بالا عکس اضافه کنید',
      loading: 'در حال بارگذاری...',
      successCreate: 'دسته‌بندی با موفقیت ایجاد شد',
      successUpload: 'عکس با موفقیت آپلود شد',
      successDeleteCategory: 'دسته‌بندی با موفقیت حذف شد',
      successDeleteItem: 'عکس با موفقیت حذف شد',
      confirmDeleteCategory: 'دسته‌بندی و تمام عکس‌های آن حذف خواهند شد. مطمئنید؟',
      confirmDeleteItem: 'این عکس حذف خواهد شد. مطمئنید؟',
      modalOk: 'متوجه شدم',
      modalCancel: 'انصراف',
      modalDelete: 'حذف',
      emptyTitle: 'بدون عنوان',
      maxTitle: 'حداکثر {max} کاراکتر',
      optional: 'اختیاری',
      maxSize: 'حداکثر ۵ مگابایت',
      imageLimit: 'تعداد عکس‌های این دسته به حداکثر (۵ عدد) رسیده است.',
      allowedTypes: 'فقط JPG، PNG، WebP و GIF پذیرفته می‌شوند',
      titleRequired: 'عنوان عکس را وارد کنید',
      titleTooLong: 'عنوان نباید بیشتر از {max} کاراکتر باشد',
      descTooLong: 'توضیحات نباید بیشتر از {max} کاراکتر باشد',
      uploadButton: 'در حال آپلود...',
      createCategoryButton: 'افزودن دسته‌بندی',
      categoryFull: '(تکمیل شده)',
      categoryCountLabel: '{count}/{max} عکس',
      categoryFullText: 'تکمیل شده'
    },
    portfolioGallery: {
      defaultTitle: 'نمونه کار',
      counter: '{index} از {total}',
      close: 'بستن',
      prev: 'قبلی',
      next: 'بعدی'
    },
    manageReviews: {
      average: 'میانگین امتیاز از {count} نظر',
      replyLabel: 'پیام پاسخ شما',
      replyPlaceholder: 'پاسخ خود را برای این نظر بنویسید...',
      cancel: 'انصراف',
      send: 'ارسال پاسخ',
      sending: 'در حال ارسال...',
      userFallback: 'کاربر',
      empty: 'هنوز نظری ثبت نشده است',
      replySuccess: 'پاسخ با موفقیت ارسال شد',
      replyError: 'ارسال پاسخ با خطا مواجه شد'
    },
    qrCode: {
      ownerOnly: 'فقط مالک سالن می‌تواند این صفحه را ببیند',
      loading: 'در حال بارگیری...',
      loadError: 'خطا در دریافت QR Code',
      noInfo: 'اطلاعات QR Code دریافت نشد',
      title: 'QR Code سالن شما',
      scanInfo: 'مشتریان با اسکن این QR Code می‌توانند برای رزرو نوبت در سالن شما وارد شوند',
      linkLabel: 'لینک QR Code:',
      download: '📥 دانلود تصویر',
      print: '🖨️ چاپ',
      instructions: 'نحوه استفاده:',
      instruction1: 'این QR Code را دانلود یا چاپ کنید',
      instruction2: 'آن را در مغازه خود نصب کنید',
      instruction3: 'مشتریان می‌توانند اسکن کنند',
      instruction4: 'وارد سالن شما شده و رزرو کنند',
      back: '🏠 بازگشت',
      errorTitle: '❌ خطا',
      returnHome: 'بازگشت',
      printTitle: 'QR Code - {salonName}'
    },
    common: {
      close: 'بستن',
      cancel: 'لغو',
      confirm: 'تأیید',
      save: 'ذخیره',
      back: 'بازگشت',
      submit: 'ارسال',
      loading: 'در حال بارگذاری...',
      search: 'جستجو',
      noResults: 'نتیجه‌ای یافت نشد',
      error: 'خطا',
      success: 'موفق',
      required: 'الزامی',
      next: 'بعدی',
      previous: 'قبلی',
      today: 'امروز',
      noData: 'داده‌ای موجود نیست',
    }
  },
  en: {
    header: {
      home: 'Home',
      myBookings: 'My Bookings',
      ownerBookings: 'Salon Bookings',
      admin: 'Admin Panel',
      support: 'Support',
      login: 'Log in',
      signup: 'Sign up',
      logout: 'Log out',
      userAs: 'Signed in as',
      toggle: 'فارسی',
      theme: 'Toggle theme',
      themeDark: 'Dark',
      themeLight: 'Light',
      supportTelegram: 'Telegram support',
      mobileMenu: 'Mobile menu',
      brandTitle: 'Salonify',
      brandSubtitle: 'Online booking',
      switchToPersian: 'Switch to Persian',
      switchToEnglish: 'Switch to English',
    },
    auth: {
      loginTitle: 'Log in',
      loginSubtitle: 'Welcome to online salon booking',
      username: 'Username',
      email: 'Email',
      password: 'Password',
      forgotPassword: 'Forgot password',
      submit: 'Log in',
      loading: 'Logging in...',
      noAccount: 'Don’t have an account?',
      createAccount: 'Create one',
      quickLogin: 'Fast and secure sign-in',
      resetSent: 'Recovery link sent',
      resetInfo: 'If this account exists, a recovery link will be sent to the registered email.',
      resetError: 'Please enter your username before sending the recovery link.',
      invalidLink: 'Recovery link is invalid.',
      showPassword: 'Show password',
      hidePassword: 'Hide password',
      loginSuccess: 'Login successful',
      loginFailed: 'Login failed. Please try again.',
      usernameMissing: 'Please enter your username',
      passwordMissing: 'Please enter your password',
      usernameInvalid: 'Username does not exist or is incorrect',
      passwordInvalid: 'Password is incorrect',
      accountDisabled: 'This account has been disabled',
      networkError: 'Network error. Please try again.',
      resetFailed: 'Sending recovery link failed. Please try again.',
      resetSuccess: 'Password changed successfully.'
    },
    signup: {
      title: 'Create account',
      subtitle: 'Sign up to book and manage appointments',
      submit: 'Sign up',
      loading: 'Signing up...',
      alreadyHaveAccount: 'Already have an account?',
      loginLink: 'Log in',
      roleCustomer: 'Customer',
      roleOwner: 'Salon owner',
      roleStaff: 'Staff',
      accountType: 'Account type',
      personalInfo: 'Personal information',
      salonInfo: 'Salon information',
      passwordSection: 'Password',
      createAccountButton: 'Create account',
      createAccountLoading: 'Creating account...',
      haveAccountPrompt: 'Already have an account?',
      signupIntro: 'Enter your information',
      signupFooter: 'Start using the online booking platform',
      signupFooterSub: 'Fast and free signup',
      roleCustomerDesc: 'Book appointments online',
      roleOwnerDesc: 'Manage your salon and bookings',
      genderLabel: 'Gender',
      genderMale: 'Male',
      genderFemale: 'Female',
      selectCity: 'Select city',
      cityModalTitle: 'Select city',
      citySearchPlaceholder: 'Search...',
      cityNotFound: 'No city found',
      showPassword: 'Show password',
      hidePassword: 'Hide password',
      usernamePlaceholder: 'Username',
      emailPlaceholder: 'example@email.com',
      firstNamePlaceholder: 'First name',
      lastNamePlaceholder: 'Last name',
      phonePlaceholder: '09123456789',
      cityPlaceholder: 'Select city',
      salonNamePlaceholder: 'Salon name',
      salonCityPlaceholder: 'Salon city',
      salonPhonePlaceholder: 'Salon phone number',
      salonAddressPlaceholder: 'Full salon address',
      passwordPlaceholder: 'Password',
      passwordConfirmPlaceholder: 'Confirm password',
      fieldRequired: 'This field is required',
      usernameRequired: 'Username is required',
      usernameMin: 'Minimum 3 characters',
      usernameAscii: 'Only English letters and numbers',
      emailRequired: 'Email is required',
      emailInvalid: 'Please enter a valid email (example: user@example.com)',
      passwordRequired: 'Password is required',
      passwordMin: 'Password must be at least 6 characters',
      passwordConfirmRequired: 'Password confirmation is required',
      passwordsMismatch: 'Passwords do not match',
      phoneRequired: 'Phone number is required',
      phoneInvalid: 'Phone number must be at least 10 digits',
      cityRequired: 'City is required',
      salonNameRequired: 'Salon name is required for owners',
      salonCityRequired: 'Salon city is required for owners',
      salonGenderRequired: 'Salon gender is required for owners',
      salonAddressRequired: 'Salon address is required for owners',
      salonPhoneInvalid: 'Salon phone number is not valid (minimum 10 digits)',
      generalError: 'Please fix the highlighted errors',
      success: 'Account created successfully',
      usernameTaken: 'This username is already taken',
      emailTaken: 'This email is already registered',
      phoneTaken: 'This phone number is already registered',
      salonPhoneTaken: 'This salon phone number is already registered',
      passwordTooShort: 'Password must be at least 8 characters',
      passwordTooCommon: 'Password is too common',
      passwordNumeric: 'Password cannot be entirely numeric',
      emailFormat: 'Email format is invalid (example: user@example.com)',
      phoneNumberInvalid: 'Phone number is invalid (minimum 10 digits)',
      salonPhoneNumberInvalid: 'Salon phone number is invalid (minimum 10 digits)',
      salonFieldRequired: 'This field is required',
      signupError: 'Please correct the highlighted errors',
    },
    resetPassword: {
      title: 'Set a new password',
      subtitle: 'Choose a new password for your account',
      newPassword: 'New password',
      confirmPassword: 'Confirm password',
      submit: 'Change password',
      loading: 'Changing password...',
      successRedirect: 'Redirecting to login...',
      passwordRequired: 'Please enter a new password',
      confirmRequired: 'Please repeat the password',
      mismatch: 'Passwords do not match',
      networkError: 'Network error. Please try again.',
      invalidLink: 'Recovery link is invalid.',
      successMessage: 'Password changed successfully.',
      changeFailed: 'Password change failed.',
    },
    home: {
      heroTitle: 'Book salon services online',
      heroSubtitle: 'Choose the service you want and reserve a time that works for you',
      sectionTitle: 'A few clicks to book an appointment',
      sectionSubtitle: 'You are only a few clicks away from booking your appointment',
      sectionTitleOwner: 'A different experience in booking',
      sectionSubtitleOwner: 'Professional tools for quick and reliable salon management',
      howItWorksTitle: 'How it works',
      howItWorksSubtitle: 'Book your appointment in three simple steps',
      howItWorksDesc: 'From search to booking, you’re only a few clicks away',
      howItWorksStep1Title: 'Find the salon',
      howItWorksStep1Desc: 'Search by name or city to find the salon you want in our platform',
      howItWorksStep2Title: 'Choose the service',
      howItWorksStep2Desc: 'See the list of services, prices, and durations, and choose the one you want',
      howItWorksStep3Title: 'Book it',
      howItWorksStep3Desc: 'Pick a suitable time and your booking is created in seconds',
      whoForTitle: 'Who is it for?',
      whoForSubtitle: 'Perfect for customers and salon owners',
      customerFeatureTitle: 'Find the right salon',
      customerFeatureDesc: 'Search, book, and head to the salon without waiting!',
      customerBookingTitle: 'Book online',
      customerBookingDesc: 'Choose the service, price, and timing you need — your booking is created in seconds',
      customerBestTitle: 'Choose the best',
      customerBestDesc: 'Ratings and reviews from previous customers help you pick the best salon with confidence',
      ownerFeatureTitle: 'Smart booking management',
      ownerFeatureDesc: 'Full control of reservations and precise daily scheduling',
      ownerVisibilityTitle: 'Be seen among the best',
      ownerVisibilityDesc: 'Show your salon professionally alongside the best in the city to attract new customers',
      ownerOptimizationTitle: 'Save time and grow revenue',
      ownerOptimizationDesc: 'Reduce cancellations and manage scheduling precisely to improve efficiency and income',
      ownerPanelTitleText: 'Professional management panel',
      ownerPanelDesc: 'Reporting tools and dedicated support for simple and fast business management',
      welcomeTitle: 'Welcome to Salonify',
      welcomeSubtitle: 'A platform for online salon booking; find your preferred salon, choose the service you want, and book an appointment in seconds',
      welcomeSubtitle2: 'No phone calls or in-person visits required. Browse registered salons on the platform and manage your own bookings. Salon owners can also control services and appointments through the management panel.',
      dashboardTitle: 'Salon monitoring dashboard',
      dashboardSubtitle: 'Essential tools and live analytics based on your real system status.',
      bookingLinkTitle: 'Booking link',
      bookingLinkDesc: 'This is your salon’s unique booking link. Copy it and place it in your Instagram bio, SMS, or other contact channels so customers can book directly.',
      bookingLinkButton: 'Copy booking link',
      bookingLinkCopied: 'Link copied successfully!',
      servicesSummaryTitle: 'Services and pricing status',
      activeServicesLabel: 'Active services for customers:',
      inactiveServicesLabel: 'Temporarily inactive services:',
      averagePriceLabel: 'Average salon service value:',
      totalServicesLabel: 'Total services defined:',
      salonIdentityTitle: 'Salon digital identity',
      salonIdentityDesc: 'A summary of the structure and details customers see in your booking profile. Additional information can be edited in the settings tab.',
      salonCityLabel: 'Registered city:',
      salonGenderLabel: 'Salon specialization:',
      salonRatingLabel: 'Average customer rating:',
      salonPhoneLabel: 'Contact phone:',
      topSalonsTitle: 'Top salons',
      topSalonsSubtitle: 'The top 5 salons with the highest customer satisfaction',
      viewAllTitle: 'Looking for more salons?',
      viewAllSubtitle: 'On the salons page, you can filter by city, gender, and search to find exactly what you want.',
      viewAllButton: 'View all salons',
      moreSalonsLabel: '{count}+ salons on the platform',
      moreSalonsText: 'More salons coming soon',
      platformTitle: 'Users trust our platform at a glance',
      platformSubtitle: 'Enjoy a fast, secure, and convenient online booking experience with our platform',
      platformSalons: 'Partner salons',
      platformBookings: 'Successful bookings',
      platformSatisfaction: 'User satisfaction',
      noSalonsTitle: 'No salon has been registered yet',
      noSalonsText: 'New salons will be added soon',
      customerSignup: 'Sign up as a customer',
      ownerSignup: 'Sign up as a salon owner',
      customerSearchHint: 'Search registered salons by name or city',
      customerPriceHint: 'View exact service prices and durations before booking',
      customerBookingHint: 'Book and manage appointments through your personal account',
      ownerServicesHint: 'Create and manage salon services with prices and durations',
      ownerBookingsHint: 'View and manage bookings made by customers',
      ownerVisibilityHint: 'Show your salon to new customers through the platform',
      searchTitle: 'Search salons',
      searchSubtitle: 'Search by salon name',
      searchPlaceholder: 'Search salon name...',
      searchEmpty: 'No salons found',
      searchEmptyHint: 'No salon was found with that name',
      searchHint: 'Search salon name',
      salonCount: 'salon',
      salonsCountPlural: 'salons',
      bookNow: 'Book now',
      viewServices: 'View services',
      openHours: 'Opening hours',
      contact: 'Contact',
      services: 'Services',
      ourServices: 'Our services',
      popularSalons: 'Popular salons',
      about: 'About us',
      aboutText: 'An online booking platform for fast and convenient access to salon services',
      joinNow: 'Get started now',
      ownerPanelTitle: 'Professional salon management panel',
      ownerPanelHeading: 'Manage salon',
      ownerPanelIntro: 'Hello {name}; welcome to your salon management dashboard. Optimize your appointments and services with the tools below.',
      ownerHeroTitle: 'Salon owners',
      ownerHeroPoint1: 'Define and manage salon services with prices and durations',
      ownerHeroPoint2: 'View and manage customer bookings',
      ownerHeroPoint3: 'Show your salon to new customers through the platform',
      ownerHeroButton: 'Sign up my salon',
      salonGenderMale: '♂ Men only',
      salonGenderFemale: '♀ Women only',
      noRating: 'No rating',
      notProvided: 'Not provided',
      customerGreeting: 'Welcome',
      customerFallback: 'Dear customer',
      ownerFallback: 'Dear manager',
      customerHeading: 'Find the best salon ✨',
      customerHeadingGender: 'Find the best {gender} salons ✨',
      customerPromo: 'Search, book, and head to the salon without waiting!',
      customerPromoGender: 'Search, book, and only see {gender} salons!',
      whyTitle: 'Why Salonify?',
      whyCustomer: 'No phone calls, no waiting — just book and go',
      whyOwner: 'Manage everything from one platform',
      featureSearchDesc: 'Search among registered salons, view ratings and reviews, and choose with confidence',
      featureTimingTitle: 'No waiting, arrive on time',
      featureTimingDesc: 'Book services and appointments quickly without delays through the platform',
      ownerSummary: 'A summary of your active services in the Salonify booking system, along with the estimated value and average real transaction prices of your salon.',
      close: 'Close',
      applyFilter: 'Apply filter',
      selectCity: 'Select city',
      selectCitySubtitle: 'Choose the city you want',
      allCities: 'All cities',
      noSalonsFound: 'No salons found',
      noSalonsFoundHint: 'No salon was found with that name',
      searchByName: 'Search salon name',
      resultsCount: '{count} salons',
      serviceSingular: 'service',
      servicePlural: 'services',
      itemSingular: 'item',
      itemPlural: 'items',
      reviewSingular: 'review',
      reviewPlural: 'reviews',
      loadError: 'Loading salon information failed.',
      salonsLoadError: 'Loading the salon list failed.'
    },
    salons: {
      title: 'Salonify salons',
      subtitle: 'Choose from {count} salons in your city',
      back: 'Back',
      searchPlaceholder: 'Search salon name or city...',
      genderBadge: 'Only {gender} salons are shown',
      cityBadge: 'Only salons in your city are shown',
      forYouBadge: 'For you',
      filterAll: 'All',
      clearFilters: 'Clear filters',
      countLabel: 'salons',
      smartSortBanner: 'Results are sorted based on location, rating, and popularity',
      emptyFiltersHint: 'Try changing or clearing your filters',
      sortTitle: 'Sort',
      sortSubtitle: 'Choose how salons are displayed',
      sortSmart: 'Smart suggestion',
      sortSmartDesc: 'Based on location, rating, and reviews',
      sortRating: 'Highest rating',
      sortRatingDesc: 'Salons with the most stars',
      sortNewest: 'Newest',
      sortNewestDesc: 'Most recently joined salons',
      sortReviews: 'Most reviews',
      sortReviewsDesc: 'Most popular among customers',
      sortName: 'Name (A-Z)',
      sortNameDesc: 'Alphabetical sorting',
    },
    services: {
      heroTitle: 'Salon services',
      heroSubtitle: 'Select the service you want and book an appointment',
      genderMale: 'Men',
      genderFemale: 'Women',
      activeServices: 'active service',
      activeServicesPlural: 'active services',
      disabledTitle: 'This salon is currently unavailable',
      disabledText: 'Unavailable until further notice.',
      priceNote: 'Displayed prices are base rates and may change depending on your request.',
      aboutOwner: 'Beauty specialist',
      address: 'Address',
      phone: 'Phone',
      openHours: 'Opening hours',
      noServices: 'No services available',
      book: 'Book this service',
      loading: 'Loading services...',
      serviceList: 'Services list',
      salonInfo: 'Salon information',
      reviews: 'Customer reviews',
      bookNow: 'Book an appointment',
    },
    booking: {
      title: 'Book an appointment',
      subtitle: 'Choose a convenient date and time',
      selectDate: 'Select date',
      selectTime: 'Select time',
      continue: 'Continue',
      confirm: 'Confirm booking',
      success: 'Booking was successful',
      error: 'Booking failed. Please try again.',
      loading: 'Loading...',
      service: 'Service',
      salon: 'Salon',
      price: 'Price',
      time: 'Time',
      date: 'Date',
      customerName: 'Customer name',
      phone: 'Phone',
      email: 'Email',
      notes: 'Notes',
      back: 'Back',
      noSalonSelectedTitle: 'No salon selected',
      noSalonSelectedMessage: 'Please choose a salon from the home page first so you can book an appointment.',
      goHome: 'Go to home',
      tryAgain: 'Try again',
      goBack: 'Go back',
      calendarErrorTitle: 'Calendar loading error',
      calendarErrorMessage: 'The available dates could not be loaded. Please check your connection and try again.',
      selected: 'Selected',
      today: 'Today',
      full: 'Full',
      closed: 'Closed',
      fullDayBooked: 'All appointments for this day are booked',
      salonClosedToday: 'The salon is closed on this day',
    },
    bookings: {
      title: 'My bookings',
      subtitle: 'Your booking status',
      empty: 'You have not booked any appointment yet',
      loading: 'Loading bookings...',
      service: 'Service',
      time: 'Time',
      status: 'Status',
      cancel: 'Cancel',
      confirm: 'Confirm',
      noBookings: 'No bookings to display',
      accountInfoTitle: 'Account information',
      accountInfoUsername: 'Username',
      accountInfoPhone: 'Phone number',
      accountInfoEmail: 'Email',
      bookingsListTitle: 'Bookings list',
      searchTitle: 'Search bookings',
      searchPhone: 'Phone number',
      searchPlaceholder: 'Example: 09121234567',
      searchButton: 'Search bookings',
      searchLoading: 'Searching...',
      searchHint: 'Sign in to your account for easier access and to view all your bookings.',
      loadingBookings: 'Loading bookings...',
      totalBookings: 'Total bookings',
      confirmedStatus: 'Confirmed',
      pendingStatus: 'Pending',
      cancelledStatus: 'Cancelled',
      noBookingsFoundTitle: 'No bookings found',
      noBookingsFoundHint: 'Enter your phone number to view your bookings.',
      noBookingsFoundEmpty: 'You have not booked any appointment yet or the booking with these details does not exist.',
      bookingNotCancellable: 'This booking can no longer be cancelled.',
      cancelConfirmTitle: 'Confirm cancellation',
      cancelConfirmText: 'Are you sure you want to cancel this booking?',
      cancelConfirmDetail: 'This action cannot be undone. If you cancel it, the booking for {service} will be removed.',
      cancelConfirmHint: 'To continue, click Yes, cancel it. If you change your mind, you can close this window.',
      cancelConfirmCancel: 'Cancel',
      cancelConfirmSubmit: 'Yes, cancel it',
      cancelConfirmSubmitting: 'Cancelling...',
      successTitle: 'Success',
      successConfirm: 'Booking confirmed successfully.',
      successCancel: 'Booking cancelled successfully.',
      goHome: 'Back to home',
      noSalonSelectedTitle: 'No salon selected',
      noSalonSelectedText: 'Please choose a salon from the home page first.',
      confirmBookingAction: 'Confirm booking',
      cancelBookingAction: 'Cancel booking',
      cancelCustomerBooking: 'Cancel booking',
      bookingStarted: 'Started',
      daysLabel: 'days',
      hoursLabel: 'hours',
      minutesLabel: 'minutes',
      unknownStatus: 'Unknown',
    },
    ownerBookings: {
      title: 'Manage bookings',
      subtitle: 'View and manage salon bookings',
      back: 'Back to panel',
      salonInfo: 'Salon information',
      salonName: 'Salon name',
      city: 'City',
      phone: 'Phone',
      bookingsList: 'Bookings list',
      loading: 'Loading bookings...',
      salonNameLabel: 'Salon name',
      cityLabel: 'City',
      phoneLabel: 'Phone',
    },
    admin: {
      title: 'Salon admin panel',
      overview: 'Overview',
      services: 'Services',
      addService: 'Add service',
      addServiceTitle: 'Service name',
      addServicePrice: 'Service price',
      addServiceDuration: 'Duration',
      addServiceCategory: 'Category',
      addServiceSubmit: 'Add service',
      workingHours: 'Working hours',
      bookings: 'Bookings',
      reviews: 'Customer reviews',
      portfolio: 'Portfolio',
      ownerInfo: 'Owner info',
      qrCode: 'Salon QR code',
      settings: 'Salon settings',
      filterAll: 'All',
      filterPending: 'Pending approval',
      filterConfirmed: 'Confirmed',
      filterCancelled: 'Cancelled',
      serviceNameRequired: 'Please enter a service name',
      servicePriceRequired: 'This service price must be greater than zero',
      serviceDuplicate: 'Duplicate service',
      serviceAddError: 'Error adding service',
      serviceUpdateError: 'Error updating service',
      serviceEnableSuccess: 'Service enabled. It is now visible to customers.',
      serviceDisableSuccess: 'Service disabled. It is no longer visible to customers.',
      serviceNameLabel: 'Service name',
      servicePriceLabel: 'Service price',
      serviceDurationLabel: 'Duration (minutes)',
      serviceNamePlaceholder: 'Example: haircut',
      servicePricePlaceholder: 'Example: 500000',
      serviceDurationPlaceholder: 'Example: 30',
      workingHourSelectDay: 'Please select a day',
      workingHourSelectShift: 'Please add at least one shift',
      workingHourMaxShifts: 'A maximum of 2 shifts per day is allowed',
      workingHourTimeOrder: 'The start time must be before the end time',
      workingHourSaveSuccessNext: 'Day {day} saved. Now set {nextDay}.',
      workingHourSaveSuccessEnd: 'Working hours for {day} saved successfully',
      workingHourDeleteError: 'Error deleting working hours',
      workingHourDeleteConfirmTitle: 'Delete work shift',
      workingHourDeleteConfirmMessage: 'Are you sure you want to delete this shift?',
      workingHoursDeleteConfirmationCancel: 'Cancel',
      workingHoursDeleteConfirmationSubmit: 'Yes, delete it',
      activeDaysLabel: 'Active days',
      totalShiftsLabel: 'Total shifts',
      multiShiftDaysLabel: 'Multi-shift days',
      salonInfoTitle: 'Salon information',
      salonNameLabel: 'Salon name',
      cityLabel: 'City',
      phoneLabel: 'Phone',
      mobileLabel: 'Mobile',
      addressLabel: 'Address',
      contactEditButton: 'Edit phone and mobile numbers',
      contactPhoneLabel: 'Landline (optional)',
      contactPhonePlaceholder: 'Example: 02112345678',
      contactMobileLabel: 'Mobile (required)',
      salonStatusTitle: 'Salon status',
      salonDisabledStatus: 'The salon is currently disabled',
      salonDisabledUntil: 'Until {date}',
      salonActiveStatus: 'The salon is active',
      activateSalonButton: 'Activate salon',
      deactivateSalonButton: 'Deactivate salon',
      disableSalonTitle: 'Disable salon',
      disableSalonDurationLabel: 'Disable duration (days) - optional',
      disableSalonDurationPlaceholder: 'Example: 7 (for one week)',
      disableSalonDurationHint: 'If left empty, the salon remains disabled until you activate it yourself',
      disableSalonReasonLabel: 'Reason for disabling - optional',
      disableSalonReasonPlaceholder: 'Example: holidays, renovation...',
      disableSalonSubmit: 'Disable',
      disableSalonCancel: 'Cancel',
      disableSalonProcessing: 'Processing...',
      ownerSavingState: 'Saving...',
      ownerSaveButton: 'Save details',
      ownerContactSaveButton: 'Save',
      ownerContactCancelButton: 'Cancel',
      workingHoursStatusActive: 'Active',
      workingHoursStatusRest: 'Rest',
      workingHoursShiftCount: '{count} shifts',
      contactMobilePlaceholder: 'Example: 09123456789',
      contactSaveButton: 'Save',
      contactCancelButton: 'Cancel',
      contactMobileRequiredTitle: 'Mobile number is required',
      contactMobileRequiredMessage: 'To save the information, you must enter a mobile number.',
      contactSaveSuccess: 'Contact details saved successfully',
      contactSaveErrorTitle: 'Error saving contact information',
      ownerInfoDescriptionTooLong: 'Your description must not exceed 500 characters.',
      ownerInfoRequired: 'Please enter at least one item (image or description).',
      ownerInfoSaveSuccess: 'Owner information saved successfully',
      ownerInfoSaveErrorTitle: 'Error saving information',
      ownerInfoSaveErrorMessage: 'Error saving owner information',
      imageSizeError: 'Image size must not exceed 5MB',
      imageTypeError: 'Only JPEG, PNG, WebP, and GIF images are accepted',
      errorTitle: 'Error',
      successTitle: 'Success',
      noDataTitle: 'Loading...',
      qrDownloadButton: 'Download',
      qrPrintButton: 'Print',
      qrIdLabel: 'QR Code ID:',
      qrLinkLabel: 'QR Code link:',
      qrHowToUseTitle: '🎯 How to use:',
      qrHowToUseStep1: 'Download the QR code image',
      qrHowToUseStep2: 'Print it and place it in your shop',
      qrHowToUseStep3: 'Customers scan it with their phone camera',
      qrHowToUseStep4: 'Your salon page opens',
      qrHowToUseStep5: 'The customer books an appointment',
      qrPrintTitle: 'Print QR Code',
      qrScanHint: 'Scan to book an appointment',
      qrLoadingText: 'Loading...',
      positionEditorVertical: 'Vertical (top/bottom)',
      positionEditorReset: 'Reset center',
      positionEditorConfirm: 'Confirm position ✓',
      bookingTableCustomer: 'Customer',
      bookingTableService: 'Service',
      bookingTableDateTime: 'Date and time',
      bookingTableStatus: 'Status',
      bookingTableContact: 'Contact info',
      noWorkingHoursForDay: 'No shifts have been saved for this day yet.',
      qrCodeErrorOwner: 'Only the salon owner can view the QR code',
      qrCodeErrorAuth: 'Please log in to your account',
      qrCodeErrorGeneric: 'Error loading QR code',
      salonLoadError: 'Error loading salon information',
      servicePriceHint: 'To activate this service, first enter a price greater than zero.',
      accessDenied: 'Access denied. Only owners and staff can access this area.',
      welcomeUser: 'Welcome, {username}',
      manageServicesTitle: 'Manage services',
      manageServicesSubtitle: 'See, edit, or enable and disable salon services.',
      manageServicesAddButton: 'New service',
      manageServicesAddModalTitle: 'Add new service',
      manageServicesEditModalTitle: 'Edit service',
      manageServicesSave: 'Save service',
      manageServicesUpdate: 'Save changes',
      manageServicesEmptyTitle: 'No service has been added yet',
      manageServicesEmptySubtitle: 'Start by adding a new service',
      manageServicesInfoTitle: 'When you click the active/inactive button:',
      manageServicesInfoActive: 'If the service is active, customers can see it and book it',
      manageServicesInfoInactive: 'If the service is inactive, customers cannot see or book it',
      manageServicesInfoNoDelete: 'The service is not deleted; only its status changes',
      manageServicesCancel: 'Cancel',
      manageServicesSaving: 'Saving...',
      workingHoursTitle: 'Manage working hours',
      workingHoursSubtitle: 'Review days visually, arrange shifts with drag and drop, and apply them to multiple days in one step.',
      workingHoursAddButton: 'Add schedule',
      workingHoursCloseButton: 'Close',
      workingHoursFormTitle: 'Set working hours day by day',
      workingHoursFormSubtitle: 'Set each day separately, save it, and use the next-day button to continue. Thursday and Friday can also have different hours.',
      workingHoursCurrentDay: 'Current day',
      workingHoursPrevDay: 'Previous',
      workingHoursNextDay: 'Next day',
      workingHoursSavedStatus: 'Saved',
      workingHoursFreeStatus: 'Free',
      workingHoursPresetReady: 'Preset ready for this day',
      workingHoursResetDay: 'Reset this day\'s shifts',
      workingHoursResetCurrent: 'Reset current day',
      workingHoursAddShift: '+ Add second shift',
      workingHoursMaxShifts: 'A maximum of 2 shifts per day is allowed',
      workingHoursSaveAndNext: 'Save this day and go to {nextDay}',
      workingHoursSaveAndEnd: 'Save and finish',
      workingHoursSaveCurrentDay: 'Only the day selected above is saved each time. After saving, you continue with the next day.',
      bookingsTitle: 'Manage bookings',
      bookingsEmptyTitle: 'No bookings have been made yet',
      bookingsEmptySubtitle: 'Customers have not booked any appointments yet',
      bookingsFilterLabel: 'Status filter',
      bookingsCountLabel: '{count} bookings',
      bookingsNoMatchTitle: 'No booking exists with this status',
      reviewsTitle: 'Customer reviews',
      portfolioTitle: 'Portfolio manager',
      ownerInfoTitle: 'Owner information',
      qrCodeTitle: 'Salon QR code',
      settingsTitle: 'Salon settings',
      ownerInfoSectionTitle: 'Salon information',
      ownerPreviewLabel: 'Final preview',
      ownerPositionButton: 'Adjust position',
      ownerPositionHelpTitle: 'Adjust image position',
      ownerPositionHelpText: 'Drag the image inside the frame to choose the best circular crop',
      ownerPositionReset: 'Reset center',
      ownerPositionConfirm: 'Confirm position ✓',
      ownerImageSelectLabel: 'Choose image',
      ownerImageChangeLabel: 'Change image',
      ownerImageLabel: 'Owner image (circle)',
      ownerImageHint: 'JPEG, PNG, WebP, or GIF (max 5MB)',
      ownerDescriptionLabel: 'About yourself (max 500 characters)',
      ownerDescriptionPlaceholder: 'Write about yourself and your expertise...',
      ownerDescriptionCount: '{count} / 500 characters',
      ownerAccessDenied: 'QR Code is only visible to the salon owner',
      workingHoursShiftLabel: 'Shift {number}',
      workingHoursDeleteButton: 'Delete',
      workingHoursMoveButton: 'Move',
      workingHoursStartTimeLabel: 'Start time',
      workingHoursEndTimeLabel: 'End time',
      workingHoursNextDayHint: 'Next: {day}',
      workingHoursLastDayHint: 'Last day of the week',
      workingHoursDaySummary: 'Only this day will be saved',
      workingHoursStatusLabel: 'Status',
      workingHoursNoShiftsBadge: 'Closed',
      workingHoursDeleteConfirmationTitle: 'Delete shift',
      workingHoursDeleteConfirmationMessage: 'Are you sure you want to delete this shift?',
      weekDay0: 'Saturday',
      weekDay1: 'Sunday',
      weekDay2: 'Monday',
      weekDay3: 'Tuesday',
      weekDay4: 'Wednesday',
      weekDay5: 'Thursday',
      weekDay6: 'Friday',
      presetMorning: 'Morning shift',
      presetAfternoon: 'Afternoon',
      presetSplit: 'Morning / evening',
      presetFull: 'Full day'
    },
    portfolioManager: {
      title: 'Portfolio manager',
      newCategory: 'New category',
      categoryCount: '{count}/{max}',
      addCategory: 'Add category',
      addCategoryLoading: 'Creating...',
      categoryName: 'Category name',
      categoryDescription: 'Description',
      uploadTitle: 'Image title',
      uploadDescription: 'Description',
      uploadHint: 'Click or drop files here',
      uploadError: 'Upload failed',
      deleteCategory: 'Delete category',
      deleteItem: 'Delete image',
      noCategories: 'No categories yet',
      noCategoriesHint: 'Create a category first, then add images',
      noItems: 'No images added yet',
      noItemsHint: 'Add images from the form above',
      loading: 'Loading...',
      successCreate: 'Category created successfully',
      successUpload: 'Image uploaded successfully',
      successDeleteCategory: 'Category deleted successfully',
      successDeleteItem: 'Image deleted successfully',
      confirmDeleteCategory: 'This category and all its images will be deleted. Are you sure?',
      confirmDeleteItem: 'This image will be deleted. Are you sure?',
      modalOk: 'Got it',
      modalCancel: 'Cancel',
      modalDelete: 'Delete',
      emptyTitle: 'Untitled',
      maxTitle: 'Maximum {max} characters',
      optional: 'Optional',
      maxSize: 'Maximum 5 MB',
      imageLimit: 'This category has reached the maximum of 5 images.',
      allowedTypes: 'Only JPG, PNG, WebP and GIF files are accepted',
      titleRequired: 'Please enter an image title',
      titleTooLong: 'Title must not exceed {max} characters',
      descTooLong: 'Description must not exceed {max} characters',
      uploadButton: 'Uploading...',
      createCategoryButton: 'Add category',
      categoryFull: '(full)',
      categoryCountLabel: '{count}/{max} images',
      categoryFullText: 'Full'
    },
    portfolioGallery: {
      defaultTitle: 'Portfolio item',
      counter: '{index} of {total}',
      close: 'Close',
      prev: 'Previous',
      next: 'Next'
    },
    manageReviews: {
      average: 'Average rating from {count} reviews',
      replyLabel: 'Your reply',
      replyPlaceholder: 'Write your reply to this review...',
      cancel: 'Cancel',
      send: 'Send reply',
      sending: 'Sending...',
      userFallback: 'User',
      empty: 'No reviews yet',
      replySuccess: 'Reply sent successfully',
      replyError: 'Failed to send reply'
    },
    qrCode: {
      ownerOnly: 'Only the salon owner can view this page',
      loading: 'Loading...',
      loadError: 'Error loading QR code',
      noInfo: 'QR code information could not be loaded',
      title: 'Your salon QR code',
      scanInfo: 'Customers can scan this QR code to enter your salon and book an appointment',
      linkLabel: 'QR code link:',
      download: '📥 Download image',
      print: '🖨️ Print',
      instructions: 'How to use it:',
      instruction1: 'Download or print this QR code',
      instruction2: 'Place it in your shop',
      instruction3: 'Customers can scan it',
      instruction4: 'They can enter your salon and book an appointment',
      back: '🏠 Back',
      errorTitle: '❌ Error',
      returnHome: 'Back',
      printTitle: 'QR Code - {salonName}'
    },
    common: {
      close: 'Close',
      cancel: 'Cancel',
      confirm: 'Confirm',
      save: 'Save',
      back: 'Back',
      submit: 'Submit',
      loading: 'Loading...',
      search: 'Search',
      noResults: 'No results found',
      error: 'Error',
      success: 'Success',
      required: 'Required',
      next: 'Next',
      previous: 'Previous',
      today: 'Today',
      noData: 'No data available',
    }
  }
};

const getPreferredLanguage = () => {
  if (typeof window === 'undefined') return 'fa';
  const saved = window.localStorage.getItem(STORAGE_KEY);
  return saved === 'en' ? 'en' : 'fa';
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getPreferredLanguage);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'en' ? 'ltr' : 'rtl';
    document.documentElement.setAttribute('data-lang', language);
    localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const t = (key, fallback = '', params = {}) => {
    const current = translations[language] || translations.fa;
    const value = key.split('.').reduce((acc, part) => acc?.[part], current);
    const resolved = value || fallback || key;
    return Object.entries(params).reduce((acc, [name, replacement]) => acc.replace(new RegExp(`\\{${name}\\}`, 'g'), String(replacement)), resolved);
  };

  const value = useMemo(() => ({ language, setLanguage, t }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
