# Generated by Django 4.2.28 on 2026-02-23 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('theme_color', models.CharField(default='#ff5500', max_length=7)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'مردانه'), ('female', 'زنانه')], max_length=10, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shops.salon')),
            ],
        ),
        migrations.CreateModel(
            name='SalonWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='shops.salon')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('salon', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
