# Generated by Django 4.2.28 on 2026-02-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='disable_reason',
            field=models.TextField(blank=True, help_text='دلیل غیرفعال شدن سالن', null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='disabled_until',
            field=models.DateTimeField(blank=True, help_text='سالن تا این تاریخ غیرفعال است', null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='وضعیت سالن'),
        ),
    ]
