# Generated by Django 4.2.27 on 2026-06-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_portfoliocategory_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='owner_description',
            field=models.TextField(blank=True, help_text='توضیح درباره مالک سالن', null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='owner_image',
            field=models.ImageField(blank=True, help_text='عکس مالک سالن', null=True, upload_to='salon_owners/%Y/%m/%d/'),
        ),
    ]
