# Generated by Django 4.2.28 on 2026-06-12 09:51

from django.db import migrations, models
import uuid


def add_qr_codes(apps, schema_editor):
    """تولید QR code منحصر به فرد برای هر سالن"""
    Salon = apps.get_model('shops', 'Salon')
    for salon in Salon.objects.all():
        salon.qr_code = uuid.uuid4()
        salon.save(update_fields=['qr_code'])


def reverse_add_qr_codes(apps, schema_editor):
    """برگرداندن QR codes"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_salon_owner_description_salon_owner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='qr_code',
            field=models.UUIDField(blank=True, default=None, editable=False, help_text='QR کد منحصربه‌فرد برای سالن', null=True, unique=True),
        ),
        migrations.RunPython(add_qr_codes, reverse_add_qr_codes),
    ]
