# Generated by Django 4.2.28 on 2026-06-12 09:50

from django.db import migrations
import uuid


def populate_qr_codes(apps, schema_editor):
    """تولید QR code منحصر به فرد برای هر سالن"""
    Salon = apps.get_model('shops', 'Salon')
    for salon in Salon.objects.all():
        if not salon.qr_code:
            salon.qr_code = uuid.uuid4()
            salon.save(update_fields=['qr_code'])


def reverse_populate_qr_codes(apps, schema_editor):
    """پاک کردن QR codes"""
    Salon = apps.get_model('shops', 'Salon')
    Salon.objects.all().update(qr_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_add_qr_code_to_salon'),
    ]

    operations = [
        migrations.RunPython(populate_qr_codes, reverse_populate_qr_codes),
    ]
