# Generated by Django 4.2.28 on 2026-06-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_add_qr_code_to_salon'),
        ('shops', '0008_populate_qr_codes'),
    ]

    operations = [
    ]
