# Generated by Django 4.2.28 on 2026-06-12 09:55

from django.db import migrations
import uuid


def regenerate_qr_codes(apps, schema_editor):
    """تولید مجدد QR codes برای سالن‌های که QR code ندارند"""
    Salon = apps.get_model('shops', 'Salon')
    updated = 0
    for salon in Salon.objects.all():
        if not salon.qr_code:
            salon.qr_code = uuid.uuid4()
            salon.save(update_fields=['qr_code'])
            updated += 1
    print(f"\n✅ {updated} سالن به‌روز‌رسانی شد با QR codes جدید")


def reverse_regenerate_qr_codes(apps, schema_editor):
    """برگرداندن QR codes"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_merge_20260612_1325'),
    ]

    operations = [
        migrations.RunPython(regenerate_qr_codes, reverse_regenerate_qr_codes),
    ]
