# Generated by Django 4.2.28 on 2026-06-12 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_regenerate_qr_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='QR کد منحصربه‌فرد برای سالن', unique=True),
        ),
    ]
