# Generated by Django 4.2.28 on 2026-06-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_fix_qr_code_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
