# Generated by Django 4.2.30 on 2026-06-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_alter_salon_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salonworkinghours',
            options={'ordering': ['day_of_week', 'sort_order', 'start_time']},
        ),
        migrations.AddField(
            model_name='salonworkinghours',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='ترتیب نمایش شیفت در همان روز'),
        ),
    ]
