# Generated by Django 4.2.30 on 2026-06-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_alter_service_options_alter_service_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='service',
            name='unique_service_name_per_salon',
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('salon', 'name'), name='unique_active_service_name_per_salon'),
        ),
    ]
