# Generated by Django 4.2.30 on 2026-06-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='mobile',
            field=models.CharField(blank=True, help_text='شماره موبایل سالن (برای اطلاع\u200cرسانی به مشتری استفاده می\u200cشود)', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='phone',
            field=models.CharField(blank=True, help_text='تلفن ثابت سالن (اختیاری)', max_length=12, null=True),
        ),
    ]
