# Generated by Django 4.2.30 on 2026-06-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_salon_mobile_alter_salon_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salon',
            name='mobile',
            field=models.CharField(blank=True, help_text='شماره موبایل سالن (از ثبت\u200cنام مالک گرفته می\u200cشود)', max_length=12, null=True, unique=True),
        ),
    ]
