export const IRAN_CITIES = [
  { value: 'تهران', labelFa: 'تهران', labelEn: 'Tehran' },
  { value: 'مشهد', labelFa: 'مشهد', labelEn: 'Mashhad' },
  { value: 'اصفهان', labelFa: 'اصفهان', labelEn: 'Isfahan' },
  { value: 'شیراز', labelFa: 'شیراز', labelEn: 'Shiraz' },
  { value: 'تبریز', labelFa: 'تبریز', labelEn: 'Tabriz' },
  { value: 'قم', labelFa: 'قم', labelEn: 'Qom' },
  { value: 'کاشان', labelFa: 'کاشان', labelEn: 'Kashan' },
  { value: 'کرمانشاه', labelFa: 'کرمانشاه', labelEn: 'Kermanshah' },
  { value: 'بندرعباس', labelFa: 'بندرعباس', labelEn: 'Bandar Abbas' },
  { value: 'اهواز', labelFa: 'اهواز', labelEn: 'Ahvaz' },
  { value: 'یزد', labelFa: 'یزد', labelEn: 'Yazd' },
  { value: 'کرج', labelFa: 'کرج', labelEn: 'Karaj' },
  { value: 'اراک', labelFa: 'اراک', labelEn: 'Arak' },
  { value: 'همدان', labelFa: 'همدان', labelEn: 'Hamedan' },
  { value: 'خرم آباد', labelFa: 'خرم آباد', labelEn: 'Khorramabad' },
  { value: 'سنندج', labelFa: 'سنندج', labelEn: 'Sanandaj' },
  { value: 'بجنورد', labelFa: 'بجنورد', labelEn: 'Bojnord' },
  { value: 'سبزوار', labelFa: 'سبزوار', labelEn: 'Sabzevar' },
  { value: 'رشت', labelFa: 'رشت', labelEn: 'Rasht' },
  { value: 'بابل', labelFa: 'بابل', labelEn: 'Babol' },
  { value: 'گرگان', labelFa: 'گرگان', labelEn: 'Gorgan' },
  { value: 'رامسر', labelFa: 'رامسر', labelEn: 'Ramsar' },
  { value: 'ساری', labelFa: 'ساری', labelEn: 'Sari' },
  { value: 'اردبیل', labelFa: 'اردبیل', labelEn: 'Ardabil' },
  { value: 'زنجان', labelFa: 'زنجان', labelEn: 'Zanjan' },
  { value: 'اردستان', labelFa: 'اردستان', labelEn: 'Ardestan' },
  { value: 'بوشهر', labelFa: 'بوشهر', labelEn: 'Bushehr' },
  { value: 'خوی', labelFa: 'خوی', labelEn: 'Khoy' },
  { value: 'مهاباد', labelFa: 'مهاباد', labelEn: 'Mahabad' },
  { value: 'مریوان', labelFa: 'مریوان', labelEn: 'Marivan' },
  { value: 'قائم‌شهر', labelFa: 'قائم‌شهر', labelEn: 'Qaem Shahr' },
  { value: 'لاهیجان', labelFa: 'لاهیجان', labelEn: 'Lahijan' },
  { value: 'علی‌آباد', labelFa: 'علی‌آباد', labelEn: 'Aliabad' },
  { value: 'انزلی', labelFa: 'انزلی', labelEn: 'Anzali' },
  { value: 'چالوس', labelFa: 'چالوس', labelEn: 'Chalus' },
  { value: 'نوشهر', labelFa: 'نوشهر', labelEn: 'Nowshahr' },
  { value: 'نیشابور', labelFa: 'نیشابور', labelEn: 'Neyshabur' },
];